rename linux-xanmod-custom to lilium, upgrade mesa

diff --git a/linux-lilium/PKGBUILD b/linux-lilium/PKGBUILD
--- a/linux-lilium/PKGBUILD
+++ b/linux-lilium/PKGBUILD
@@ -4,7 +4,7 @@
 # Contributor: Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
 
 
-_microarchitecture=93
+_microarchitecture=92
 use_numa=y
 use_tracers=y
 _compiler=clang
@@ -16,19 +16,22 @@ if [ "${_compiler}" = "clang" ]; then
   _compiler_flags="CC=clang HOSTCC=clang LLVM=1 LLVM_IAS=1"
 fi
 
-pkgbase=linux-xanmod-custom
+pkgbase=linux-lilium
 _major=6.11
-pkgver=${_major}.1
+pkgver=${_major}.4
 _branch=6.x
 xanmod=1
 pkgrel=${xanmod}
-pkgdesc='Linux Xanmod - Current Stable (CURRENT) with Custom Patches'
+pkgdesc='Linux Kernel - Current Stable (CURRENT) with Custom Patches'
 url="http://www.xanmod.org/"
 arch=(x86_64)
 _lucjan="https://raw.githubusercontent.com/sirlucjan/kernel-patches/master/${_major}/"
 _cachy="https://raw.githubusercontent.com/CachyOS/kernel-patches/master/${_major}/"
 _tkg="https://raw.githubusercontent.com/Frogging-Family/linux-tkg/master/linux-tkg-patches/${_major}/"
+_xanmod="https://gitlab.com/xanmod/linux-patches/-/raw/master/linux-6.11.y-xanmod/"
 _commit_ck=2870d6ac146aa658af60bb18a9c7503efe5992d4
+
+_bore=5.6.1
 
 license=(GPL2)
 makedepends=(
@@ -40,19 +43,46 @@ fi
 options=('!strip')
 _srcname="linux-${pkgver}-xanmod${xanmod}"
 
-
-source=("https://cdn.kernel.org/pub/linux/kernel/v${_branch}/linux-${_major}.tar."{xz,sign}
-
-        "https://master.dl.sourceforge.net/project/xanmod/releases/edge/${pkgver}-xanmod${xanmod}/patch-${pkgver}-xanmod${xanmod}.xz"
-        
+source=("https://cdn.kernel.org/pub/linux/kernel/v${_branch}/linux-${pkgver}.tar."{xz,sign}
+        "https://cdn.kernel.org/pub/linux/kernel/projects/rt/$_major/patch-$_major-rt7.patch."{xz,sign}
         "choose-gcc-optimization.sh"
-        
-        "0001-bore.patch"
-        "${_lucjan}amd-pstate-patches-v2/0001-amd-6.11-merge-changes-from-dev-tree.patch"
-        "${_lucjan}intel-pstate-patches-all/0001-intel-pstate-patches.patch"
+        "config"
 
+        "https://github.com/firelzrd/bore-scheduler/raw/refs/heads/main/patches/stable/linux-$_major-bore/0001-linux$_major.y-bore$_bore.patch"
+        
+        # Xanmod Feature
+        "${_xanmod}binder/0001-binder-turn-into-module.patch"
+        "${_xanmod}binder/0002-binder-give-binder_alloc-its-own-debug-mask-file.patch"
+        "${_xanmod}binder/0003-wait-allow-to-use-__wake_up_pollfree-from-GPL-module.patch"
+        "${_xanmod}binder/0004-file-export-file_close_fd-instead-of-close_fd_get_fi.patch"
+        "${_xanmod}clearlinux/0001-sched-wait-Do-accept-in-LIFO-order-for-cache-efficie.patch"
+        "${_xanmod}clearlinux/0002-firmware-Enable-stateless-firmware-loading.patch"
+        "${_xanmod}clearlinux/0003-locking-rwsem-spin-faster.patch"
+        "${_xanmod}clearlinux/0004-drivers-initialize-ata-before-graphics.patch"
+        "${_xanmod}net/mac80221/0001-mac80211-ignore-AP-power-level-when-tx-power-type-is.patch"
+        "${_xanmod}net/netfilter/0001-netfilter-Add-netfilter-nf_tables-fullcone-support.patch"
+        "${_xanmod}net/netfilter/0002-netfilter-add-xt_FLOWOFFLOAD-target.patch"
+        "${_xanmod}net/tcp/cloudflare/0001-tcp-Add-a-sysctl-to-skip-tcp-collapse-processing-whe.patch"
+        "${_xanmod}pci_acso/0001-PCI-Enable-overrides-for-missing-ACS-capabilities.patch"
+        "${_xanmod}userns/0001-sysctl-add-sysctl-to-disallow-unprivileged-CLONE_NEW.patch"
+        "${_xanmod}zen/0001-ZEN-input-evdev-Use-call_rcu-when-detaching-client.patch"
+        "${_xanmod}xanmod/0007-XANMOD-block-mq-deadline-Increase-write-priority-to-.patch"
+        "${_xanmod}xanmod/0009-XANMOD-block-Set-rq_affinity-to-force-complete-I-O-r.patch"
+        "${_xanmod}xanmod/0010-XANMOD-blk-wbt-Set-wbt_default_latency_nsec-to-2msec.patch"
+        "${_xanmod}xanmod/0012-XANMOD-dcache-cache_pressure-50-decreases-the-rate-a.patch"
+        "${_xanmod}xanmod/0015-XANMOD-sched-autogroup-Add-kernel-parameter-and-conf.patch"
+        "${_xanmod}xanmod/0016-XANMOD-cpufreq-tunes-ondemand-and-conservative-gover.patch"
+        "${_xanmod}xanmod/0015-XANMOD-sched-autogroup-Add-kernel-parameter-and-conf.patch"
+        "${_xanmod}zen/0002-ZEN-dm-crypt-Disable-workqueues-for-crypto-ops.patch"
+        
+        "${_lucjan}bbr3-patches/0001-tcp-bbr3-initial-import.patch"
+        "${_lucjan}ntsync-patches-all/0001-ntsync-patches.patch"
+        "${_lucjan}futex-patches/0001-futex-6.11-Add-entry-point-for-FUTEX_WAIT_MULTIPLE-o.patch"
+
+        "${_lucjan}powercap-patches/0001-powercap-intel_rapl-Add-support-for-AMD-family-1Ah.patch"
+        "${_lucjan}intel-pstate-patches-all/0001-intel-pstate-patches.patch"
         "${_lucjan}le9uo-patches/0001-mm-6.11-add-le9uo.patch"
-        "${_lucjan}cachyos-fixes-patches-v2/0001-cachyos-fixes-patches.patch"
+        "${_lucjan}cachyos-fixes-patches-v6/0001-cachyos-fixes-patches.patch"
 
         "${_lucjan}kbuild-patches/0001-kbuild-patches.patch"
         "${_lucjan}mm-patches/0001-mm-patches.patch"
@@ -63,9 +93,12 @@ source=("https://cdn.kernel.org/pub/linux/kernel/v${_branch}/linux-${_major}.tar
 
         "${_lucjan}openvpn-patches-v2-all/0001-openvpn-patches.patch"
         "${_lucjan}perf-patches/0001-perf-6.11-merge-changes-from-dev-tree.patch"
+        "${_lucjan}amd-cache-optimizer-patches/0001-amd-cache-optimizer-patches.patch"
         "${_lucjan}cpu-cachyos-patches-v6/0001-cpu-cachyos-patches.patch"
 
         "${_tkg}0013-optimize_harder_O3.patch"
+        "${_lucjan}amd-patches/0001-amd-patches.patch"
+        "${_lucjan}amd-hfi-patches-all/0001-amd-hfi-patches.patch"
         "${_cachy}misc/0001-acpi-call.patch"
         "${_tkg}0003-glitched-base.patch"
         )
@@ -88,38 +121,67 @@ export KBUILD_BUILD_HOST=${KBUILD_BUILD_HOST:-archlinux}
 export KBUILD_BUILD_USER=${KBUILD_BUILD_USER:-makepkg}
 export KBUILD_BUILD_TIMESTAMP=${KBUILD_BUILD_TIMESTAMP:-$(date -Ru${SOURCE_DATE_EPOCH:+d @$SOURCE_DATE_EPOCH})}
 
-prepare() {
-  cd linux-${_major}
+apply_patch() {
+    local patch_file=$(realpath "$1" 2>/dev/null)
+    local output
+  
+    # Cek apakah file patch ada
+    if [[ ! -f "$patch_file" ]]; then
+        echo "Error: Patch File '$patch_file' not found."
+        return 1
+    fi
 
-  msg2 "Apply Xanmod patch"
-  patch -Np1 -i ../patch-${pkgver}-xanmod${xanmod}
+    echo "Applying $patch_file"
+    local output=`patch -Np1 -F2 --input=$patch_file`
+    local status=$?
+    echo $status
+    if [[ $output == *"FAILED"* ]]; then
+      echo "Error: Failed to apply patch '$patch_file'."
+      echo $output
+      exit 1
+    fi
+
+    echo "Patch '$patch_file' applied."
+    echo "Output:"
+    echo $output
+    return 0
+  }
+
+prepare() {
+  mv linux-${pkgver} linux-${_major}
+  cd linux-${_major}
 
   msg2 "Setting version..."
   echo "-$pkgrel" > localversion.10-pkgrel
   echo "${pkgbase#linux-xanmod}" > localversion.20-pkgname
 
+  msg2 "Applying RT patch"
+  apply_patch "../patch-6.11-rt7.patch"
+  apply_patch "../patch-6.11-rt7.patch"
+
   # Archlinux patches
+  msg2 "Applying Patches"
   local src
   for src in "${source[@]}"; do
     src="${src%%::*}"
     src="${src##*/}"
     [[ $src = *.patch ]] || continue
     msg2 "Applying patch $src..."
-    # patch -Np1 -F2 --input="../$src" -r -
-    OUT="$(patch -Np1 -F2 --input="../$src" -r -)" || echo "${OUT}" | grep "Skipping patch" -q || (echo "$OUT" && false);
-
+    apply_patch "../$src"
+    # OUT="$(patch -Np1 -F2 --input="../$src" -r -)" || echo "${OUT}" | grep "Skipping patch" -q | echo "${OUT}" || (echo "$OUT" && false);
   done
 
   # Applying configuration
-  # cp -vf CONFIGS/xanmod/${_compiler}/config_x86-64-v2 .config
   msg2 "Copy configuration"
-  cp -vf CONFIGS/xanmod/gcc/config_x86-64-v3 .config
+  cp ../config .config
 
+  # EROFS as module
+  scripts/config --module CONFIG_EROFS_FS
 
   # enable BORE Scheduler
   scripts/config -e CONFIG_SCHED_BORE
 
-  scripts/config  --set-val X86_64_VERSION 3
+  scripts/config  --set-val X86_64_VERSION 1
 
   # enable LTO_CLANG_THIN
   if [ "${_compiler}" = "clang" ]; then
@@ -180,7 +242,7 @@ prepare() {
   fi
 
   msg2 "Set HOSTNAME"
-  scripts/config --set-val CONFIG_DEFAULT_HOSTNAME "XANMOD-X86_64-V3"
+  scripts/config --set-val CONFIG_DEFAULT_HOSTNAME "CUSTORIZER"
 
   msg2 "AMD PSTATE"
   scripts/config  -e CONFIG_X86_AMD_PSTATE
@@ -193,7 +255,7 @@ prepare() {
 
   msg2 "Enabling FULLCONENAT..."
   scripts/config --module IP_NF_TARGET_FULLCONENAT \
-                  --module NETFILTER_XT_TARGET_FULLCONENAT
+                 --module NETFILTER_XT_TARGET_FULLCONENAT
   
 
   msg2 "Enabling KBUILD_CFLAGS -O3..."
