upgrade

diff --git a/llvm-bootstrap/PKGBUILD b/llvm-bootstrap/PKGBUILD
--- a/llvm-bootstrap/PKGBUILD
+++ b/llvm-bootstrap/PKGBUILD
@@ -1,7 +1,7 @@
 pkgname=llvm-bootstrap
 pkgdesc="LLVM Toolchain with clang, clang-tools-extra, openmp, compiler-rt, polly, lldb, lld"
-pkgver=20.1.3
-pkgrel=2
+pkgver=20.1.4
+pkgrel=1
 arch=('x86_64')
 url="https://llvm.org/"
 license=('custom:Apache 2.0 with LLVM Exception')
@@ -65,7 +65,10 @@ _patch() {
 
 prepare() {
 
-  mv llvm-project-llvmorg-${pkgver} llvm-project
+  mv "${srcdir:?}/llvm-project-llvmorg-${pkgver}" llvm-project || (
+    echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
+    exit 1
+  )
 
   cd "${srcdir:?}/llvm-project" || (
     echo -e "\E[1;31mCan't cd to ${srcdir}/llvm-project directory! Prepare Failed! \E[0m"
