use clang to build clang

diff --git a/llvm-all/PKGBUILD b/llvm-all/PKGBUILD
--- a/llvm-all/PKGBUILD
+++ b/llvm-all/PKGBUILD
@@ -1,7 +1,7 @@
 pkgname=llvm-all
 pkgdesc="LLVM Toolchain with clang, clang-tools-extra, compiler-rt, polly, lldb, lld"
 pkgver=19.1.7
-pkgrel=1
+pkgrel=2
 arch=('x86_64')
 url="https://llvm.org/"
 license=('custom:Apache 2.0 with LLVM Exception')
@@ -9,20 +9,21 @@ license=('custom:Apache 2.0 with LLVM Exception')
 provides=(
   'llvm' "llvm=${pkgver}" 'llvm-libs' 'llvm-ocaml' 'clang' "clang=${pkgver}"
   'clang-analyzer' 'clang-tools-extra' 'polly' 'compiler-rt' 'openmp'
-  'lld' 'lldb' 'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt' 'mlir'
+  'lld' 'lldb' 'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt'
+  'llvm-offload'
   )
 
 replaces=(
   'llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
-  'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp' 'mlir'
-  'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt'
+  'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp'
+  'libc++' 'libc++abi' 'libc++experimental' 'llvm-bolt' 'llvm-offload'
   )
 
 conflicts=(
   'llvm' 'llvm-libs' 'llvm-ocaml' 'clang' 'clang-analyzer'
   'clang-tools-extra' 'polly' 'compiler-rt' 'lld' 'lldb' 'openmp'
   'llvm-git' 'llvm-libs-git' 'llvm-ocaml-git' 'libc++'
-  'libc++abi' 'libc++experimental' 'llvm-bolt' 'mlir'
+  'libc++abi' 'libc++experimental' 'llvm-bolt' 'llvm-offload'
   )
 
 depends=('libelf' 'libffi' 'libedit' 'libxml2' 'ncurses' 'xz' 'zlib' 'gcc-libs')
@@ -30,8 +31,8 @@ _ocaml_ver=4.14.0
 makedepends=(
   'git' 'ninja' 'cmake' 'clang' 'llvm'
   "ocaml>=${_ocaml_ver}" 'ocaml-ctypes' 'ocaml-findlib'
-  'python-setuptools' 'python-psutil' 'python-sphinx'
-  'python-recommonmark' 'ocaml-stdlib-shims' 'mimalloc'
+  'python-setuptools' 'python-psutil' 'python-sphinx' 'python-docutils'
+  'python-myst-parser' 'ocaml-stdlib-shims' 'mimalloc'
 )
 makedepends_x86_64=('lib32-gcc-libs')
 source=(
@@ -81,17 +82,36 @@ prepare() {
     exit 1
   )
 
-  pushd polly/lib/External
+  # # MLIR
+  # ## /usr/bin/ld: cannot find -lLLVMCodeGenTypes: No such file or directory
+  # sed -i 's|LLVM_LINK_COMPONENTS|IGNORE_THAT|g' mlir/tools/mlir-tblgen/CMakeLists.txt
+
+  # ## FuncOps.h.inc: No such file or directory
+  # pushd mlir  || (
+  #   echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
+  #   exit 1
+  # )
+
+  # curl -L https://github.com/llvm/llvm-project/pull/97885.patch | patch -p2
+
+  # popd || (
+  #   echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+  #   exit 1
+  # )
+  # # MLIR DONE
+
+  pushd polly/lib/External  || (
+    echo -e "\E[1;31mpushd - Package Failed!  \E[0m"
+    exit 1
+  )
+
   chmod +x update-isl.sh
   ./update-isl.sh isl-0.27
-  popd
-
-  if [ -n "$CC" ] && [ -n "$CXX" ]; then
-    _extra_build_flags+=(
-      -DCMAKE_C_COMPILER="$CC"
-      -DCMAKE_CXX_COMPILER="$CXX"
-    )
-  fi
+  
+  popd  || (
+    echo -e "\E[1;31mpopd - Package Failed!  \E[0m"
+    exit 1
+  )
 
 }
 
@@ -102,43 +122,56 @@ build() {
     exit 1
   )
 
-  export CFLAGS="$CFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition"
-  export CXXFLAGS="$CXXFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition"
+  cflags="$CFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition"
+  cxxflags="$CXXFLAGS -fno-plt -fomit-frame-pointer -fno-semantic-interposition"
+  ldflags="$LDFLAGS"
+  
+  unset CFLAGS
+  unset CXXFLAGS
+  unset LDFLAGS
 
-    _extra_build_flags+=(
-      -DCMAKE_BUILD_TYPE=Release
-      -DCMAKE_INSTALL_PREFIX=/usr
-      -DFFI_INCLUDE_DIR="$(pkg-config --variable=includedir libffi)"
-      -DLLVM_BINUTILS_INCDIR=/usr/include
-      -DLLVM_BUILD_RUNTIME=ON
-      -DLLVM_HOST_TRIPLE="${CHOST:?}"
-      -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON
-      -DLLVM_BUILD_LLVM_DYLIB=ON
-      -DLLVM_LINK_LLVM_DYLIB=ON
-      -DLLVM_INSTALL_UTILS=ON
-      -DLLVM_ENABLE_CURL=ON
-      -DLLVM_ENABLE_RTTI=ON
-      -DLLVM_ENABLE_FFI=ON
-      -DLLVM_ENABLE_PIC=ON
-      -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;cross-project-tests;lld;lldb;compiler-rt;mlir;polly"
-      -DLLVM_ENABLE_RUNTIMES="libcxxabi;pstl;libcxx;openmp"
-      -DCLANG_LINK_CLANG_DYLIB=ON
-      -DCLANG_DEFAULT_PIE_ON_LINUX=ON
-      -DLIBCXXABI_USE_LLVM_UNWINDER=OFF
-      -DLIBCXX_INSTALL_MODULES=ON
-      -DLLDB_USE_SYSTEM_SIX=1
-      -DLIBOMP_INSTALL_ALIASES=OFF
-      -DCOMPILER_RT_INSTALL_PATH=/usr/lib/clang/${pkgver%%.*}
-      -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF
-      -DPOLLY_ENABLE_GPGPU_CODEGEN=ON
-    )
+  _extra_build_flags+=(
+    -DCMAKE_C_FLAGS="$cflags"
+    -DCMAKE_CXX_FLAGS="$cxxflags"
+    -DCMAKE_BUILD_TYPE=Release
+    -DCMAKE_INSTALL_PREFIX=/usr
+    -DFFI_INCLUDE_DIR="$(pkg-config --variable=includedir libffi)"
+    -DLLVM_BINUTILS_INCDIR=/usr/include
+    -DLLVM_STATIC_LINK_CXX_STDLIB=ON
+    -DLLVM_HOST_TRIPLE="${CHOST:?}"
+    -DLLVM_BUILD_LLVM_DYLIB=ON
+    -DLLVM_LINK_LLVM_DYLIB=ON
+    -DLLVM_INSTALL_UTILS=ON
+    -DLLVM_BUILD_RUNTIME=ON
+    -DLLVM_ENABLE_CURL=ON
+    -DLLVM_ENABLE_RTTI=ON
+    -DLLVM_ENABLE_FFI=ON
+    -DLLVM_ENABLE_PIC=ON
+    -DLLVM_USE_PERF=ON
+    -DLLVM_ENABLE_PROJECTS="bolt;clang;clang-tools-extra;lld;lldb;polly"
+    -DLLVM_ENABLE_RUNTIMES="libcxxabi;pstl;libcxx;openmp;compiler-rt"
+    -DCLANG_LINK_CLANG_DYLIB=ON
+    -DCLANG_DEFAULT_PIE_ON_LINUX=ON
+    -DLIBCXXABI_USE_LLVM_UNWINDER=OFF
+    -DLIBCXX_INSTALL_MODULES=ON
+    -DLLDB_USE_SYSTEM_SIX=1
+    -DLIBOMP_INSTALL_ALIASES=OFF
+    -DCOMPILER_RT_INSTALL_PATH=/usr/lib/clang/${pkgver%%.*}
+    -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON
+    -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF
+    -DPOLLY_ENABLE_GPGPU_CODEGEN=ON
+    -Wno-dev
+  )
 
   if ld.lld --version 2>/dev/null | grep -iq "LLD\s*[0-9]"; then
     export LD=ld.lld
     export CC_LD=lld
     export CXX_LD=lld
     export HOSTLD=ld.lld
-    _extra_build_flags+=(-DLLVM_ENABLE_LLD=ON)
+    _extra_build_flags+=(
+      -DLLVM_ENABLE_LLD=ON
+      -DLLVM_ENABLE_LTO=Thin
+      )
   fi
 
   while true; do
@@ -180,7 +213,7 @@ build() {
 
   cmake -S llvm -B build -G Ninja "${_extra_build_flags[@]}"
 
-  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/src/llvm-project/build" ninja -C build
+  ninja -C build
 
   if [[ _build_documentation -eq 1 && _build_bindings -ne 0 ]]; then
     ninja -C build ocaml_doc
